const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USERS = "ONLINE_USERS";

// New events for enhanced features
const MESSAGE_REACTION = "MESSAGE_REACTION";
const MESSAGE_SEEN = "MESSAGE_SEEN";
const USER_TYPING = "USER_TYPING";

// WebRTC Call Events
const CALL_REQUEST = "CALL_REQUEST";
const CALL_ACCEPTED = "CALL_ACCEPTED";
const CALL_REJECTED = "CALL_REJECTED";
const CALL_ENDED = "CALL_ENDED";
const ICE_CANDIDATE = "ICE_CANDIDATE";
const WEBRTC_OFFER = "WEBRTC_OFFER";
const WEBRTC_ANSWER = "WEBRTC_ANSWER";

export {
    ALERT, CALL_ACCEPTED, CALL_ENDED, CALL_REJECTED,
    // WebRTC Call Events
    CALL_REQUEST, CHAT_JOINED,
    CHAT_LEAVED, ICE_CANDIDATE, MESSAGE_REACTION,
    MESSAGE_SEEN, NEW_ATTACHMENT, NEW_MESSAGE, NEW_MESSAGE_ALERT,
    NEW_REQUEST, ONLINE_USERS, REFETCH_CHATS, START_TYPING,
    STOP_TYPING, USER_TYPING, WEBRTC_ANSWER, WEBRTC_OFFER
};

